name: Long live the King!
title: Blog for C++/Swift
description: This blog for studying algorithms, C++ and Swift.
tags:
  - Algorithm
  - C++
  - Swift
email: rhkdgus0826@gmail.com
disqus_username: papayetoo
show_hero: true
